### ISSUE TITLE
ERROR "qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found." occurred in Debian11 when "nmp run dev"

### ISSUE THREAD

**Issue by Huaweidev** [rwv/lookscanned.io#51]
Hi,
ERROR "qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found." occurred in Debian11 when "nmp run dev". I tried these commands but it didn't work:
```
apt install npm
apt install libxcb-util1
sudo apt install -qq libglu1-mesa-dev libx11-xcb-dev '^libxcb*'
python3 -m pip install PyQt5
sudo apt-get install libqt5x11extras5
```
ERROR still hapen when run `npm run dev`, what could I do to run it successfully in Debian 11:
```

> lookscanned.io@0.0.0 dev
> vite

QFactoryLoader::QFactoryLoader() checking directory path "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms" ...
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqeglfs.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqeglfs.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "eglfs"
        ]
    },
    "archreq": 0,
    "className": "QEglFSIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("eglfs")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqlinuxfb.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqlinuxfb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "linuxfb"
        ]
    },
    "archreq": 0,
    "className": "QLinuxFbIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("linuxfb")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimal.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimal.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimal"
        ]
    },
    "archreq": 0,
    "className": "QMinimalIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("minimal")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimalegl.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqminimalegl.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "minimalegl"
        ]
    },
    "archreq": 0,
    "className": "QMinimalEglIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("minimalegl")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqoffscreen.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqoffscreen.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "offscreen"
        ]
    },
    "archreq": 0,
    "className": "QOffscreenIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("offscreen")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqvnc.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqvnc.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "vnc"
        ]
    },
    "archreq": 0,
    "className": "QVncIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("vnc")
QFactoryLoader::QFactoryLoader() looking at "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so"
Found metadata in lib /usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so, metadata=
{
    "IID": "org.qt-project.Qt.QPA.QPlatformIntegrationFactoryInterface.5.3",
    "MetaData": {
        "Keys": [
            "xcb"
        ]
    },
    "archreq": 0,
    "className": "QXcbIntegrationPlugin",
    "debug": false,
    "version": 331520
}


Got keys from plugin meta data ("xcb")
QFactoryLoader::QFactoryLoader() checking directory path "/usr/bin/platforms" ...
loaded library "/usr/lib/x86_64-linux-gnu/qt5/plugins/platforms/libqxcb.so"
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.

Aborted
npm ERR! code 134
npm ERR! path /home/user/Downloads/lookscanned.io
npm ERR! command failed
npm ERR! command sh -c vite

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2022-06-07T04_45_13_061Z-debug.log
```
---
在Debian11下重新换了一套命令尝试如下:
```
sudo apt install npm
mkdir /usr/local/node
cd /usr/local/node
wget https://nodejs.org/dist/v16.15.1/node-v16.15.1-linux-x64.tar.xz
tar -xvf node-v16.15.1-linux-x64.tar.xz
vim /etc/profile
在末尾加入：
VERSION=v16.14.0
DISTRO=linux-x64
export PATH=/usr/local/node/node-$VERSION-$DISTRO/bin:$PATH
刷新配置：
source /etc/profile
npm install electron-packager -g
npm i
npm dev run
```
出现如下错误：
```
> lookscanned.io@0.0.0 dev
> vite

failed to load config from /home/user/lookscanned.io/vite.config.ts
error when starting dev server:
Error: Cannot find module 'fs/promises'
Require stack:
- /home/user/lookscanned.io/node_modules/@vuetify/loader-shared/dist/styles/writeStyles.js
- /home/user/lookscanned.io/node_modules/@vuetify/loader-shared/dist/index.js
- /home/user/lookscanned.io/node_modules/@vuetify/vite-plugin/dist/importPlugin.js
- /home/user/lookscanned.io/node_modules/@vuetify/vite-plugin/dist/index.js
- /home/user/lookscanned.io/vite.config.ts
- /home/user/lookscanned.io/node_modules/vite/dist/node/chunks/dep-59dc6e00.js
- /home/user/lookscanned.io/node_modules/vite/dist/node/cli.js
- /home/user/lookscanned.io/node_modules/vite/bin/vite.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:815:15)
    at Function.Module._load (internal/modules/cjs/loader.js:667:27)
    at Module.require (internal/modules/cjs/loader.js:887:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.<anonymous> (/home/user/lookscanned.io/node_modules/@vuetify/loader-shared/dist/styles/writeStyles.js:4:20)
    at Module._compile (internal/modules/cjs/loader.js:999:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1027:10)
    at Module.load (internal/modules/cjs/loader.js:863:32)
    at Function.Module._load (internal/modules/cjs/loader.js:708:14)
    at Module.require (internal/modules/cjs/loader.js:887:19)
npm ERR! code 1
npm ERR! path /home/user/lookscanned.io
npm ERR! command failed
npm ERR! command sh -c vite

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2022-06-08T00_39_35_631Z-debug.log

```

---
在Windows 10下，运行命令安装环境：
```
安装node.js
npm install electron-packager -g
npm i
npm dev run
```

- [ ] **能出现正常结果**：

```
  vite v2.9.9 dev server running at:

  > Local: http://localhost:3000/
  > Network: use `--host` to expose

  ready in 223ms.
```

**Comment by rwv** [comment]
This is unrelated to this project since `electron` and `qt` is not included in this project. Maybe you could check the electron's doc?
